### ISSUE TITLE
Feature request: Output as CSV

### ISSUE THREAD

**Issue by emilebosch** [kellyjonbrazil/jtbl#11]
Hi Kelly hope you're good 👋 
I thought maybe it was cool if we had a csv output. Let me know what you think <3

**Comment by kellyjonbrazil** [comment]
Hey Emile!

I have resisted it because there are other options (like `jq`), but seeing that CSV is fairly human readable it does seem to make sense. I might also add HTML table output support while adding CSV output. It will be a bit back-burner for now since I'm currently working on a bunch of /proc parsers for `jc`.

**Comment by kellyjonbrazil** [comment]
Hi @emilebosch,

I added CSV and HTML output options in the `dev` branch. Can you pull it down and test?

Thanks!

**Comment by emilebosch** [comment]
Fantastic! Will do!

**Comment by kellyjonbrazil** [comment]
I'm currently sorting columns alphabetically, but I have a way to preserve the column order a bit better that I may implement soon.

**Comment by kellyjonbrazil** [comment]
I think I have the column order figured out for the CSV output. I'll see if I can generalize that for all output now.

**Comment by kellyjonbrazil** [comment]
Fixed in v1.4.0 uploaded to PyPi. Binaries coming soon.

**Comment by emilebosch** [comment]
Wow good work, this really makes things easier! Thank you!
